### ISSUE TITLE
Class name o-layers__context breaks spec (BEM - JS)

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-layers#11]
- BEM: `o-layers__context` has no `o-layers` parent.
- JS Origami Syntax Spec: Since `o-layers__context` is a JavaScript hook, it shouldn't be a class but a [data attribute](http://origami.ft.com/docs/syntax/js/#data-attributes) `data-o-layers-js`.

**Comment by AlbertoElias** [comment]
I think it's unclear if it should be `data-o-layers-js` or `data-o-layers--js`. And what about `data-o-layers-context`?

**Comment by kaelig** [comment]
What part of the spec do you think is unclear about `-js` vs `--js`?

`data-o-layers-context` doesn't really follow the spec but maybe `data-o-layers-context-js` is acceptable?

**Comment by triblondon** [comment]
OK, in this case it should be `data-o-layers-context` as a data attribute, update the spec to remove the second dash.

**Comment by triblondon** [comment]
Updated spec.  Alberto assigning to you for the code changes needed.

**Comment by wheresrhys** [comment]
Will this be a major release? If so can we discuss one or two things next week before releasing please

**Comment by AlbertoElias** [comment]
I prepared a pr yesterday #12 for @kaelig to review

@wheresrhys We are just deprecating the old one and suggesting the new one. No one was using it I believe, so it will be a minor release

**Comment by wheresrhys** [comment]
Missed the discussion yesterday but here's my belated tuppenneth
 - a layers context identifier isn't something that js adds, so the bit of the spec about js hooks doesn't apply (as written anyway... maybe needs a slight edit)
 - the context identifier isn't just for js. As outlined in the README styles should be applied as appropriate - non-static position and non-negative z-index.

On balance I think a class of `o-layers` would be most in compliance with the spec. I don't care very much either way though.

**Comment by kaelig** [comment]
> the context identifier isn't just for js. As outlined in the README styles should be applied as appropriate - non-static position and non-negative z-index.
@wheresrhys we try to aim for a separation of JS and CSS concerns, do you have a suggestion for that?

**Comment by wheresrhys** [comment]
Having a layers context without those styles doesn't really make sense. Should separation of concerns be applied here? What would be the benefit?

**Comment by kaelig** [comment]
That's a good point @wheresrhys. Complying to the spec to the letter would not be a benefit for ease of use of the module (having two classes instead of one).

The fact that the naming doesn't comply with BEM/JS hook spec is not a huge deal since there's no other classes / selectors in this module.

We have other things to put our energy towards, closing this issue. If someone feels strongly about it, they may open a PR with code a minor version that won't break existing modules (remember there are 4 dependants: o-author-alerts, o-ft-header, o-hierarchical-nav, o-overlay that would need to be updated, we don't have time for that right now).

**Comment by AlbertoElias** [comment]
I checked when I did the pr and dependents wouldn't need to update at all.
It would just be the pr and minor release here

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by kaelig** [comment]
@AlbertoElias do you mean that the dependants all rely on `document.body` and don't use the `o-layers__context` class at all?

**Comment by AlbertoElias** [comment]
`o-layers__context` is really for products to set, not for modules. o-overlay uses the js helper method, but doesn't set an `o-layers__context` class.

**Comment by kaelig** [comment]
Thanks, and do we know if any products are using this class at all?

**Comment by AlbertoElias** [comment]
FastFT is the only product that I can think of that might be using o-layers. @wheresrhys ?

**Comment by wheresrhys** [comment]
Not directly, only via the drop downs in the origami header

On 12 January 2015 at 11:11, Alberto Elias <notifications@github.com> wrote:

> FastFT is the only product that I can think of that might be using
> o-layers. @wheresrhys <https://github.com/wheresrhys> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-layers/issues/11#issuecomment-69555751>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
